services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:stable
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      TZ: Asia/Seoul
      GENERIC_TIMEZONE: Asia/Seoul
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678/
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_CONCURRENCY_PRODUCTION_LIMIT: "1"
      N8N_CONCURRENCY_PRODUCTION_LIMIT: "1"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
